# ['Electrical Devices', 'Natural Outdoor', 'Omni-Herbivores', 'Small Mammals', 'Vehicles 1']
dataset: "cifar100"
tasks: [[22, 39, 40, 86, 87], [23, 33, 49, 60, 71],
       [15, 19, 21, 31, 38], [36, 50, 65, 74, 80],
       [8, 13, 48, 58, 90]]
