# ['Aq. Mammals', 'Insects', 'Large Carnivores', 'Omni-Herbivores']
# Classes with 100 added to them have noisy labels
dataset: "cifar100"
tasks: [[104, 130, 155, 172, 195], [6, 7, 14, 18, 24],
        [103, 142, 143, 188, 197], [15, 19, 21, 31, 38]]
